language: clojure
lein: 2.7.1
dist: trusty

# Always explicitly set sudo.  Otherwise travis' defaults may vary
# based on when the repository testing was enabled.
sudo: required

matrix:
  include:
    # terminus unit tests (spec tests)
    - env: >
        NAME=rspec
        PDB_TEST_LANG=ruby
        PUPPET_VERSION=5.3.x

    # pdb unit tests
    - env: >
        NAME=unit-openjdk8
        PDB_TEST_LANG=clojure
        PDB_TEST_SELECTOR=:unit
      jdk: openjdk8

    - env: >
        NAME=unit-oracle8
        PDB_TEST_LANG=clojure
        PDB_TEST_SELECTOR=:unit
      jdk: oraclejdk8


    # pdb + terminus + puppetserver + puppet integration tests
    - env: >
        NAME=integration-openjdk8
        PDB_TEST_LANG=clojure
        PDB_TEST_SELECTOR=:integration
        PUPPET_VERSION=5.3.x
        PUPPETSERVER_VERSION=5.1.x
      jdk: openjdk8

    - env: >
        NAME=integration-oraclejdk8
        PDB_TEST_LANG=clojure
        PDB_TEST_SELECTOR=:integration
        PUPPET_VERSION=5.3.x
        PUPPETSERVER_VERSION=5.1.x
      jdk: oraclejdk8

before_install: ext/bin/configure-int-tests
script: ext/travisci/test.sh
on_success: ext/travisci/on-success

notifications:
  email: false
  hipchat:
    rooms:
      secure: gZpfMrGsUEHKzHfDaq8S00Xd35gzwEzcAy5/VV7JOGcmXLyWlx7ojh/Ke4rJ1vOa59OlazyCt5o8uDhB0CcQnZ2Aa6ncoOyLpLLjO8/Ak8qsxPLgC4Ov/zuRA4oTvxqZtaR7Juwbeobp5lB1OSFb7o4G747tC2Ihd1Nhx717tdQ=
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Change view</a>)'
    format: html

addons:
  postgresql: "9.6"

services: postgresql
