language: clojure
lein: 2.7.1
dist: trusty

# Always explicitly set sudo.  Otherwise travis' defaults may vary
# based on when the repository testing was enabled.
sudo: required

matrix:
  include:
    # # terminus unit tests (spec tests)
    # - env: >
    #     NAME=rspec-puppet-4.0
    #     PDB_TEST_LANG=ruby
    #     PUPPET_VERSION=4.0.0

    # - env: >
    #     NAME=rspec-puppet-latest
    #     PDB_TEST_LANG=ruby
    #     PUPPET_VERSION=latest

    # # pdb unit tests
    # - env: >
    #     NAME=unit-openjdk8
    #     PDB_TEST_LANG=clojure
    #     PDB_TEST_SELECTOR=:unit
    #   jdk: openjdk8

    # - env: >
    #     NAME=unit-oracle8
    #     PDB_TEST_LANG=clojure
    #     PDB_TEST_SELECTOR=:unit
    #   jdk: oraclejdk8


    # # pdb + terminus + puppetserver + puppet integration tests
    # - env: >
    #     NAME=integration-stable-openjdk8
    #     PDB_TEST_LANG=clojure
    #     PDB_TEST_SELECTOR=:integration
    #     PUPPET_VERSION=4.8.0
    #     PUPPETSERVER_VERSION=2.7.2
    #   jdk: openjdk8

    # - env: >
    #     NAME=integration-latest-puppet-openjdk8
    #     PDB_TEST_LANG=clojure
    #     PDB_TEST_SELECTOR=:integration
    #     PUPPET_VERSION=latest
    #     PUPPETSERVER_VERSION=master
    #   jdk: openjdk8

    # - env: >
    #     NAME=integration-stable-oraclejdk8
    #     PDB_TEST_LANG=clojure
    #     PDB_TEST_SELECTOR=:integration
    #     PUPPET_VERSION=4.8.0
    #     PUPPETSERVER_VERSION=2.7.2
    #   jdk: oraclejdk8

    # - env: >
    #     NAME=integration-latest-puppet-oraclejdk8
    #     PDB_TEST_LANG=clojure
    #     PDB_TEST_SELECTOR=:integration
    #     PUPPET_VERSION=latest
    #     PUPPETSERVER_VERSION=master
    #   jdk: oraclejdk8

    # postgres 10 (optional)
    - env: >
        NAME=unit-openjdk8
        PDB_TEST_PG=10
        PDB_TEST_LANG=clojure
        PDB_TEST_SELECTOR=:unit
      jdk: openjdk8

    - env: >
        NAME=integration-latest-puppet-openjdk8
        PDB_TEST_PG=10
        PDB_TEST_LANG=clojure
        PDB_TEST_SELECTOR=:integration
        PUPPET_VERSION=latest
        PUPPETSERVER_VERSION=2.7.2
      jdk: openjdk8

before_install: echo WINDING UP $(date) && ext/travisci/install_puppetserver.sh
script: ext/travisci/test.sh

notifications:
  email: false

addons:
  postgresql: "9.6"

services: postgresql
